import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ResponsiveAppBar from '@/components/header'
import Header from '@/components/header/Header'
import Modal from '@/components/modal/modal'
import Register from '@/components/loginRegister/Register'
import Login from '@/components/loginRegister/Login'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [showModal, setShowModal] = useState(true);
  
  return (
    <>
    <ResponsiveAppBar/>
      <Head>
        <title>Easy Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header showModal={showModal} setShowModal={setShowModal} />
      <Modal showModal={showModal} setShowModal={setShowModal}>
        {/* <Login /> */}
        <Register />
      </Modal>
      
    </>
  )
}
